apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-client
  template:
    metadata:
      labels:
        app: yolo-client
    spec:
      containers:
        - name: yolo-client
          image: ekimutai/client:v1.0
          ports:
            - containerPort: 80
