apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  selector:
    app: yolo-client, yolo-backend
  ports:
    - name: http-client
      port: 8080
      targetPort: 80
    - name: http-backend
      port: 80
      targetPort: 3000 
