apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-backend
  template:
    metadata:
      labels:
        app: yolo-backend
    spec:
      containers:
        - name: yolo-backend
          image: ekimutai/client:v1.0
          ports:
            - containerPort: 3000
