version: "3.9"

services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      
    # depends_on:
      # - db
  # db:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"